# Generated by Django 5.2.9 on 2025-12-14 02:44

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinquiry',
            name='budget_range_high',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinquiry',
            name='budget_range_low',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Logo'), ('cover', 'Cover Photo'), ('portfolio', 'Portfolio'), ('gallery', 'Gallery'), ('menu', 'Menu/Service List'), ('testimonial', 'Testimonial'), ('team', 'Team Member'), ('venue', 'Venue Shot'), ('decor', 'Decor Sample'), ('food', 'Food/Catering'), ('certificate', 'Certificate/Award'), ('other', 'Other')], default='portfolio', help_text='Classification of the image', max_length=20)),
                ('display_locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('card', 'Vendor Card'), ('hero', 'Hero Banner'), ('detail_gallery', 'Detail Page Gallery'), ('detail_header', 'Detail Page Header'), ('carousel', 'Homepage Carousel'), ('thumbnail', 'Search Results Thumbnail'), ('modal', 'Modal/Popup')], max_length=20), blank=True, default=list, help_text='Where this image should appear in the UI', size=None)),
                ('title', models.CharField(blank=True, help_text='Image title or caption', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the image')),
                ('image_url', models.URLField(blank=True, help_text='S3 URL of the uploaded image', max_length=500)),
                ('image_file', models.ImageField(blank=True, help_text='Upload image (will be uploaded to S3)', null=True, upload_to='vendor_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary image for this type?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this image currently active?')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Tags for filtering (e.g., "outdoor", "traditional", "modern")', size=None)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (dimensions, file size, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='authentication.vendor')),
            ],
            options={
                'ordering': ['vendor', 'image_type', 'order'],
                'indexes': [models.Index(fields=['vendor', 'image_type'], name='authenticat_vendor__4da95f_idx'), models.Index(fields=['is_active', 'is_primary'], name='authenticat_is_acti_f617b8_idx')],
            },
        ),
    ]
