# Generated by Django 5.2.9 on 2025-12-14 02:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_vendorinquiry_budget_range_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorimage',
            name='aspect_ratio',
            field=models.CharField(choices=[('1:1', 'Square (1:1)'), ('4:3', 'Standard (4:3)'), ('16:9', 'Widescreen (16:9)'), ('21:9', 'Ultrawide (21:9)'), ('9:16', 'Portrait/Story (9:16)'), ('2:3', 'Portrait (2:3)'), ('custom', 'Custom')], default='custom', help_text='Image aspect ratio', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='height',
            field=models.IntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='is_watermarked',
            field=models.BooleanField(default=False, help_text='Does this image have a watermark?'),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Seasons')], help_text='Season this image is relevant for', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='visibility_context',
            field=models.CharField(choices=[('public', 'Public - Anyone can view'), ('authenticated', 'Authenticated Users Only'), ('premium', 'Premium Members Only'), ('vendor_only', 'Vendor Internal Use'), ('admin_only', 'Admin Only')], default='public', help_text='Who can view this image', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='width',
            field=models.IntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='vendorimage',
            name='display_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('marketplace_grid', 'Marketplace Grid View'), ('marketplace_list', 'Marketplace List View'), ('marketplace_map', 'Map Popup'), ('search_result', 'Search Result Card'), ('category_hero', 'Category Page Hero'), ('storefront_header', 'Storefront Header'), ('storefront_about', 'About Section'), ('storefront_services', 'Services Section'), ('storefront_gallery', 'Storefront Gallery'), ('storefront_contact', 'Contact Section'), ('detail_hero', 'Detail Page Hero'), ('detail_gallery', 'Detail Gallery'), ('detail_sidebar', 'Detail Sidebar'), ('detail_reviews', 'Reviews Section'), ('card_small', 'Small Card (200x200)'), ('card_medium', 'Medium Card (400x300)'), ('card_large', 'Large Card (800x600)'), ('card_featured', 'Featured Vendor Card'), ('homepage_hero', 'Homepage Hero Slider'), ('homepage_featured', 'Featured Vendors Section'), ('homepage_category', 'Category Showcase'), ('mobile_splash', 'Mobile App Splash'), ('mobile_card', 'Mobile Card View'), ('mobile_story', 'Mobile Story View'), ('social_share', 'Social Share Preview'), ('email_header', 'Email Header'), ('ad_banner', 'Advertisement Banner'), ('modal_gallery', 'Gallery Modal'), ('modal_preview', 'Quick Preview Modal'), ('lightbox', 'Lightbox View')], max_length=20), blank=True, default=list, help_text='Where this image should appear in the UI', size=None),
        ),
        migrations.AlterField(
            model_name='vendorimage',
            name='image_type',
            field=models.CharField(choices=[('logo', 'Logo'), ('logo_dark', 'Logo (Dark Mode)'), ('logo_light', 'Logo (Light Mode)'), ('favicon', 'Favicon/Small Icon'), ('profile_primary', 'Primary Profile Picture'), ('profile_team', 'Team Member Photo'), ('profile_owner', 'Owner/Founder Photo'), ('profile_artist', 'Artist/Designer Profile'), ('storefront_hero', 'Storefront Hero Banner'), ('storefront_cover', 'Storefront Cover Image'), ('storefront_featured', 'Storefront Featured Image'), ('storefront_thumbnail', 'Marketplace Thumbnail'), ('storefront_banner', 'Promotional Banner'), ('portfolio', 'Portfolio Image'), ('portfolio_featured', 'Featured Work'), ('portfolio_before', 'Before Photo'), ('portfolio_after', 'After Photo'), ('portfolio_360', '360° View'), ('venue_exterior', 'Venue Exterior'), ('venue_interior', 'Venue Interior'), ('venue_aerial', 'Aerial/Drone Shot'), ('venue_night', 'Night View'), ('venue_ceremony', 'Ceremony Space'), ('venue_reception', 'Reception Space'), ('menu_food', 'Food Menu/Samples'), ('menu_drinks', 'Drinks/Bar Menu'), ('decor_sample', 'Decor Sample'), ('setup_diagram', 'Setup/Layout Diagram'), ('social_cover', 'Social Media Cover'), ('social_post', 'Social Media Post'), ('testimonial', 'Testimonial/Review Image'), ('certificate', 'Certificate/Award'), ('press', 'Press/Media Feature'), ('gallery', 'General Gallery'), ('gallery_event', 'Event Photos'), ('gallery_behind', 'Behind the Scenes'), ('other', 'Other')], default='portfolio', help_text='Classification of the image', max_length=20),
        ),
    ]
